services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started